import React from "react";
import { Link } from "react-router-dom";
import { FiCheckCircle, FiZap, FiBriefcase, FiTrendingUp } from "react-icons/fi";

const LandingPage = () => {
  const features = [
    {
      icon: <FiBriefcase className="text-3xl" />,
      title: "Role-Specific Prep",
      description: "Customize your preparation based on your target role and experience level",
    },
    {
      icon: <FiZap className="text-3xl" />,
      title: "AI-Powered Questions",
      description: "Get relevant interview questions generated by advanced AI",
    },
    {
      icon: <FiCheckCircle className="text-3xl" />,
      title: "Track Progress",
      description: "Organize questions, add notes, and track your preparation journey",
    },
    {
      icon: <FiTrendingUp className="text-3xl" />,
      title: "Smart Answers",
      description: "Get AI-generated answers to help you understand concepts better",
    },
  ];

  return (
    <div className="min-h-screen bg-gradient-to-br from-orange-50 via-white to-orange-50/50">
      {/* Hero Section */}
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 pt-20 pb-16">
        <div className="text-center">
          <h1 className="text-5xl md:text-6xl font-bold text-gray-900 mb-6">
            Ace Your Next{" "}
            <span className="bg-gradient-to-r from-orange-500 to-orange-600 bg-clip-text text-transparent">
              Tech Interview
            </span>
          </h1>
          <p className="text-xl text-gray-600 mb-8 max-w-3xl mx-auto">
            AI-powered interview preparation platform that helps you practice with
            role-specific questions, track your progress, and master your interview skills
          </p>
          <div className="flex gap-4 justify-center">
            <Link
              to="/signup"
              className="px-8 py-4 bg-gradient-to-r from-orange-500 to-orange-600 text-white rounded-lg font-semibold text-lg hover:shadow-xl transition-all"
            >
              Get Started Free
            </Link>
            <Link
              to="/login"
              className="px-8 py-4 bg-white border-2 border-orange-500 text-orange-600 rounded-lg font-semibold text-lg hover:bg-orange-50 transition-all"
            >
              Login
            </Link>
          </div>
        </div>

        {/* Features Grid */}
        <div className="mt-24 grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-8">
          {features.map((feature, index) => (
            <div
              key={index}
              className="bg-white p-6 rounded-xl shadow-lg hover:shadow-xl transition-shadow border border-gray-100"
            >
              <div className="w-14 h-14 bg-gradient-to-r from-orange-500 to-orange-600 rounded-lg flex items-center justify-center text-white mb-4">
                {feature.icon}
              </div>
              <h3 className="text-xl font-bold text-gray-900 mb-2">{feature.title}</h3>
              <p className="text-gray-600">{feature.description}</p>
            </div>
          ))}
        </div>

        {/* CTA Section */}
        <div className="mt-24 bg-gradient-to-r from-orange-500 to-orange-600 rounded-2xl p-12 text-center text-white">
          <h2 className="text-3xl md:text-4xl font-bold mb-4">
            Ready to Start Your Preparation?
          </h2>
          <p className="text-xl mb-8 opacity-90">
            Join thousands of developers preparing for their dream jobs
          </p>
          <Link
            to="/signup"
            className="inline-block px-8 py-4 bg-white text-orange-600 rounded-lg font-semibold text-lg hover:shadow-xl transition-all"
          >
            Create Free Account
          </Link>
        </div>
      </div>
    </div>
  );
};

export default LandingPage;